### ISSUE TITLE
v0.29.1 Critical: TypeError breaks scene/front page rendering - Cannot read properties of undefined (reading 'find')

### ISSUE THREAD

**Issue by boogiemansam98** [stashapp/stash#6187]
### Describe the bug

**Stash Version:** v0.29.1 (build 869cbd49, Oct 22 2025)
**OS:** Windows

**Problem:**
Stash crashes when trying to render scenes page or front page with error:
"TypeError: Cannot read properties of undefined (reading 'find')"

**Affected Components:**
- SceneCard-a43cfcd3.js
- TagLink-781dfb54.js  
- FrontPage-92059f51.js

**Result:**
Page shows "Something went wrong" error and fails to load.

**Steps to Reproduce:**
1. Open Stash v0.29.1
2. Navigate to Scenes page or front page
3. Page crashes with TypeError

**Tested:**
- Disabled all plugins - issue persists
- Fresh browser cache - issue persists
- Occurs in fresh incognito window

**This appears to be a regression in v0.29.1 core code.**

### Steps to reproduce

1. Open Stash-app 
2. Error occurs when loading Home page & when loading Scenes tab.

### Expected behaviour

1. Expected page to load successfully displaying my customized home page &/or scenes page

### Stash version

v0.29.1 Build hash: 869cbd49 Build time: 2025-10-22 01:55:50

### Device details

Google Chrome Version 141.0.7390.108 (Official Build) (64-bit) - Windows 11 Pro latest build.

### Relevant log output

```shell
Something went wrong.
Details
TypeError: Cannot read properties of undefined (reading 'find')
    at Object.apply (http://localhost:9999/assets/index-e6132a4a.js:44:185710)
    at a
    at http://localhost:9999/assets/index-e6132a4a.js:40:13088
    at http://localhost:9999/assets/index-e6132a4a.js:40:13432
    at div
    at div
    at http://localhost:9999/assets/index-e6132a4a.js:44:18299
    at er (http://localhost:9999/assets/TagLink-781dfb54.js:1:19193)
    at http://localhost:9999/assets/SceneCard-a43cfcd3.js:1:7334
    at div
    at Object.apply (http://localhost:9999/assets/index-e6132a4a.js:44:185649)
    at div
    at div
    at div
    at r (http://localhost:9999/assets/FrontPage-92059f51.js:1:19428)
    at div
    at div
    at r (http://localhost:9999/assets/FrontPage-92059f51.js:1:22537)
    at r (http://localhost:9999/assets/FrontPage-92059f51.js:1:36704)
    at div
    at $ (http://localhost:9999/assets/FrontPage-92059f51.js:1:40005)
    at qt (http://localhost:9999/assets/FrontPage-92059f51.js:1:42371)
    at Ee (http://localhost:9999/assets/FrontPage-92059f51.js:1:44016)
    at Ut (http://localhost:9999/assets/FrontPage-92059f51.js:1:45062)
    at Qt (http://localhost:9999/assets/FrontPage-92059f51.js:1:45422)
    at div
    at div
    at Object.apply (http://localhost:9999/assets/index-e6132a4a.js:44:185670)
    at t (http://localhost:9999/assets/index-e6132a4a.js:40:9246)
    at t (http://localhost:9999/assets/index-e6132a4a.js:40:11203)
    at Suspense
    at jQ (http://localhost:9999/assets/index-e6132a4a.js:44:450938)
    at div
    at kJ (http://localhost:9999/assets/index-e6132a4a.js:220:17805)
    at LN1 (http://localhost:9999/assets/index-e6132a4a.js:72:491985)
    at Lz1 (http://localhost:9999/assets/index-e6132a4a.js:49:4033)
    at ep1 (http://localhost:9999/assets/index-e6132a4a.js:44:189335)
    at Suspense
    at Sz1 (http://localhost:9999/assets/index-e6132a4a.js:49:3813)
    at Object.apply (http://localhost:9999/assets/index-e6132a4a.js:44:185670)
    at hZ1 (http://localhost:9999/assets/index-e6132a4a.js:82:33617)
    at Zm1 (http://localhost:9999/assets/index-e6132a4a.js:44:187255)
    at t (http://localhost:9999/assets/index-e6132a4a.js:40:75765)
    at jQ (http://localhost:9999/assets/index-e6132a4a.js:44:450938)
    at grt (http://localhost:9999/assets/index-e6132a4a.js:220:17997)
    at Zne (http://localhost:9999/assets/index-e6132a4a.js:19:184225)
    at t (http://localhost:9999/assets/index-e6132a4a.js:40:5754)
    at t (http://localhost:9999/assets/index-e6132a4a.js:40:12282)
Unable to make websocket connection: see browser console for details
×Close
```

**Comment by boogiemansam98** [comment]
**Additional Context:**
- Started using Stash from v0.28.x (third latest version)
- Issue has existed in every version I've used (v0.28.x, v0.29.0, v0.29.1)
- This affects new/returning users, not just upgrades

**Comment by feederbox826** [comment]
Unable to replicate on a fresh install, did you start on v0.28? I remember there being a saved filter bug around there that would break the home screen

**Comment by boogiemansam98** [comment]
> Unable to replicate on a fresh install, did you start on v0.28? I remember there being a saved filter bug around there that would break the home screen

As stated above I havent encountered the issue on older versions of Stash when I used it a 6 months to 12 months ago. I disabled all plugins and UI adjustments and the issue still occurred. And it still occurs on the two latest builds.

**Comment by feederbox826** [comment]
Yes, I'm aware. Something in your configuration is conflicting with how stash is trying to operate and I'm unsure if it stems from one of the regressions pre 0.28 or starting with 0.28.

**Comment by WithoutPants** [comment]
Can you please reproduce using the scenes page, and include anything in the browser dev console? I'm unable to work out which part of the code is causing the crash from the posted stack trace. 

Another data point would be the `ui` section of your `config.yml`. You can also try temporarily removing the `ui` section from your config file to see if that fixes the issue.

**Comment by boogiemansam98** [comment]
Ive been using Claude Sonnet 4.5 to try decipher the specific cause of rhe issue which potentially seems according to Claude to be an error with untagged scenes and Stash with & without UI and Plugins installed and enabled crashes. The page itself i was getting I've attached via screenshot above. Claude suggested running a script in Chromes dev console to basically add a default tag to scenes not containing tags when scanning a fresh batch of scenes. And the tagging seems to cause the crashing issue to stop almost completely. I'll find the whole Claude dialogue trying to investigate the issue and get Claude to give you a more concise and clear explanation on rheir thought process on what may be causing the issue. As I am not quite knowledge about coding and server/website frameworks, etc.

**Comment by WithoutPants** [comment]
The log trace posted in the original description is from the `FrontPage` component; I'm asking for the stack trace from the scene list page.

The Claude stuff just looks to be muddying the waters to me. This appears to be something specific to your system, which indicates UI config as the most likely culprit.

**Comment by StagBullSwitch** [comment]
I'm getting a similar error since updating to 0.29.3 on Linux, although I'm getting "is not a function" rather than "cannot read properties."

Not sure if this is related, or if it's a different bug entirely.  If it's different, I'm happy to create a new bug report, rather than tacking on to this one.

It only does it sometimes, maybe 20% of the time, and if I reload the page after the error, it's always worked fine the second time. So far, anyway....

The page that fails to load shows this:

```
Something went wrong.
Details

TypeError: originalComponent is not a function
    at Object.apply (https://172.20.0.236:9999/assets/index-1d4bf35c.js:44:185649)
    at div
    at div
    at nt (https://172.20.0.236:9999/assets/Scene-10806c57.js:1:14451)
    at t (https://172.20.0.236:9999/assets/index-1d4bf35c.js:40:9246)
    at t (https://172.20.0.236:9999/assets/index-1d4bf35c.js:40:11203)
    at v (https://172.20.0.236:9999/assets/Scenes-b09898d9.js:1:5084)
    at t (https://172.20.0.236:9999/assets/index-1d4bf35c.js:40:9246)
    at t (https://172.20.0.236:9999/assets/index-1d4bf35c.js:40:11203)
    at Suspense
    at jQ (https://172.20.0.236:9999/assets/index-1d4bf35c.js:44:450938)
    at div
    at kJ (https://172.20.0.236:9999/assets/index-1d4bf35c.js:220:17949)
    at LN1 (https://172.20.0.236:9999/assets/index-1d4bf35c.js:72:491985)
    at Lz1 (https://172.20.0.236:9999/assets/index-1d4bf35c.js:49:4033)
    at ep1 (https://172.20.0.236:9999/assets/index-1d4bf35c.js:44:189335)
    at Suspense
    at Sz1 (https://172.20.0.236:9999/assets/index-1d4bf35c.js:49:3813)
    at Object.apply (https://172.20.0.236:9999/assets/index-1d4bf35c.js:44:185670)
    at hZ1 (https://172.20.0.236:9999/assets/index-1d4bf35c.js:82:33617)
    at Zm1 (https://172.20.0.236:9999/assets/index-1d4bf35c.js:44:187255)
    at t (https://172.20.0.236:9999/assets/index-1d4bf35c.js:40:75765)
    at jQ (https://172.20.0.236:9999/assets/index-1d4bf35c.js:44:450938)
    at grt (https://172.20.0.236:9999/assets/index-1d4bf35c.js:220:18141)
    at Zne (https://172.20.0.236:9999/assets/index-1d4bf35c.js:19:184225)
    at t (https://172.20.0.236:9999/assets/index-1d4bf35c.js:40:5754)
    at t (https://172.20.0.236:9999/assets/index-1d4bf35c.js:40:12282)
```


And the browser error console shows this:

```
index-1d4bf35c.js:72  VIDEOJS: WARN: videojs.extend is deprecated as of Video.js 7.22.0 and will be removed in Video.js 8.0.0
(anonymous) @ index-1d4bf35c.js:72

javascript:498  Uncaught (in promise) TypeError: tabsContainer.querySelector is not a function
    at Stash._listenForNonPageChanges (javascript:498:68)
interactive_heatmap:1   Failed to load resource: the server responded with a status of 404 (Not Found)
ScenePlayer-551e1b76.js:25  Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at t.<anonymous> (ScenePlayer-551e1b76.js:25:35105)
    at index-1d4bf35c.js:72:29344
interactive_heatmap:1   Failed to load resource: the server responded with a status of 404 (Not Found)
index-1d4bf35c.js:33  TypeError: originalComponent is not a function
    at javascript:31:24
    at Object.apply (index-1d4bf35c.js:44:185484)
    at javascript:31:24
    at jm1 (index-1d4bf35c.js:44:185522)
    at Object.apply (index-1d4bf35c.js:44:185649)
    at Yw (index-1d4bf35c.js:33:60286)
    at tL (index-1d4bf35c.js:33:69804)
    at Aie (index-1d4bf35c.js:33:108613)
    at kie (index-1d4bf35c.js:33:99912)
    at Qi1 (index-1d4bf35c.js:33:99835)
aL @ index-1d4bf35c.js:33
index-1d4bf35c.js:72  VIDEOJS: ERROR: TypeError: Cannot read properties of null (reading 'textTracks')
    at r.handleTracksChange (index-1d4bf35c.js:72:119973)
    at t.c (index-1d4bf35c.js:72:118116)
    at On.n.dispatcher.n.dispatcher (index-1d4bf35c.js:72:13460)
    at gl (index-1d4bf35c.js:72:14259)
    at t.trigger (index-1d4bf35c.js:72:19294)
    at r.handleTechLoadStart_ (index-1d4bf35c.js:72:177882)
    at t.<anonymous> (index-1d4bf35c.js:72:174479)
    at On.n.dispatcher.n.dispatcher (index-1d4bf35c.js:72:13460)
(anonymous) @ index-1d4bf35c.js:72
index-1d4bf35c.js:72  VIDEOJS: ERROR: TypeError: Cannot read properties of null (reading 'mode')
    at r.handleTracksChange (index-1d4bf35c.js:72:119127)
    at t.c (index-1d4bf35c.js:72:118116)
    at On.n.dispatcher.n.dispatcher (index-1d4bf35c.js:72:13460)
    at gl (index-1d4bf35c.js:72:14259)
    at t.trigger (index-1d4bf35c.js:72:19294)
    at r.handleTechLoadStart_ (index-1d4bf35c.js:72:177882)
    at t.<anonymous> (index-1d4bf35c.js:72:174479)
    at On.n.dispatcher.n.dispatcher (index-1d4bf35c.js:72:13460)
(anonymous) @ index-1d4bf35c.js:72
index-1d4bf35c.js:72  VIDEOJS: ERROR: TypeError: Cannot read properties of null (reading 'textTracks')
    at r.handleTracksChange (index-1d4bf35c.js:72:119973)
    at t.c (index-1d4bf35c.js:72:118116)
    at On.n.dispatcher.n.dispatcher (index-1d4bf35c.js:72:13460)
    at gl (index-1d4bf35c.js:72:14259)
    at t.trigger (index-1d4bf35c.js:72:19294)
    at r.handleTechLoadStart_ (index-1d4bf35c.js:72:177882)
    at t.<anonymous> (index-1d4bf35c.js:72:174479)
    at On.n.dispatcher.n.dispatcher (index-1d4bf35c.js:72:13460)
(anonymous) @ index-1d4bf35c.js:72
ScenePlayer-551e1b76.js:25  Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at t.<anonymous> (ScenePlayer-551e1b76.js:25:35105)
    at index-1d4bf35c.js:72:29344
cast_framework.js:64  Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "google-cast-button" has already been used with this registry
javascript:498  Uncaught (in promise) TypeError: tabsContainer.querySelector is not a function
    at Stash._listenForNonPageChanges (javascript:498:68)
```

There were a few more lines above this, one about file monitor not running, but I don't have the proper virtual python environment, so I know what that one's for.

The first line that seemed like it might be relevant is where I trimmed it, so there's probably some irrelevant stuff in that console output, but hopefully it will get you what you need.

I'm going to try uninstalling the file monitor plugin, since it's not working anyway, and see if that changes anything.

**Comment by feederbox826** [comment]
Working after reload sounds like it could be a plugin messing with it, do you mind posting a list of the plugins you have installed? also clearing cache usually helps a lot with transient errors like these

**Comment by StagBullSwitch** [comment]
Plugins installed:

AudioPlayer
AudioPlayerLite
CommunityScriptsUILibrary
Gallery Date Parser
PHash Duplicate Tagger
Scene Page Remember States
Add secondary performer image
Set Scene Cover
Star Identifier
Stash AI
Stash Userscript Library
Extended Stats
Tag Scenes From Performer Tags
Visage


I've uninstalled the File Monitor, and it just did it again.
I know Visage is also defunct, so I'll uninstall that one too, and keep testing.

I doubt it's a cache issue, as I'm currently running Stash in an incognito window, and that's where it's giving me the problem.
I haven't actually tried it in a normal mode, as I've just updated to this version yesterday.

I'll keep testing, and see if I can nail down anything better for troubleshooting.

(Incidentally, I've also never been able to get either of the AudioPlayer plugins to recognize and list MP3/M4A files, but that's a completely different issue.)

**Comment by feederbox826** [comment]
Can you disable all of the plguins and see if it still happens?

to my knowledge, all of those modify UI (except tag scenes from performers) and I highly suspect it's casuing an incompatibility issue

**Comment by feederbox826** [comment]
closing as stale - no follow up from one user and other user has additional plugins that heavily modify UI
